# Production Overlay - Backup Repository
# This overlay extends the base backup repository configuration
# with production-specific settings.
#
# Usage:
#   owlctl repo apply ../repos/backup-repository.yaml -o backup-repository-overlay.yaml --dry-run
#   owlctl repo apply ../repos/backup-repository.yaml -o backup-repository-overlay.yaml

apiVersion: owlctl.veeam.com/v1
kind: VBRRepository
metadata:
  name: Production Backup Repository
  labels:
    environment: production
    compliance: pci-dss
spec:
  description: Production backup repository - immutability enabled for ransomware protection

  # Higher concurrent task limit for production workloads
  maxTaskCount: 12

  # Extended immutability period for compliance
  makeRecentBackupsImmutableDays: 30

  # Advanced settings for production
  advancedSettings:
    decompressionCacheSize: 8192  # 8GB cache for better performance

    # Enable all monitoring integrations
    vOneIntegration: true

    # Optimized parallel processing
    parallelProcessing:
      enabled: true
      streams: 8
