# owlctl Configuration File
# Place this file in your project root or ~/.owlctl/owlctl.yaml

apiVersion: v1
kind: Config

# Groups bundle specs with a shared profile and overlay for batch operations.
# Apply a group: owlctl job apply --group sql-tier
# Diff a group:  owlctl job diff --group sql-tier
groups:
  sql-tier:
    description: SQL Server backup group — gold-tier retention
    profile: profiles/gold.yaml           # kind: Profile — base defaults
    overlay: overlays/compliance.yaml     # kind: Overlay — policy patch
    specs:
      - specs/jobs/sql-vm-01.yaml
      - specs/jobs/sql-vm-02.yaml

  web-tier:
    description: Web server backups — standard retention
    profile: profiles/standard.yaml
    specs:
      - specs/jobs/web-frontend.yaml
      - specs/jobs/web-api.yaml

# Targets define named VBR server connections.
# Use --target to switch: owlctl job apply --group sql-tier --target primary
targets:
  primary:
    url: https://vbr-prod.example.com
    description: Production VBR server

  dr:
    url: https://vbr-dr.example.com
    description: Disaster recovery site

# Usage Examples:
#
# 1. List groups and targets
#    owlctl group list
#    owlctl target list
#
# 2. Show group details (resolved paths, spec count)
#    owlctl group show sql-tier
#
# 3. Apply a group (dry-run first)
#    owlctl job apply --group sql-tier --dry-run
#    owlctl job apply --group sql-tier
#
# 4. Apply a group to a specific target
#    owlctl job apply --group sql-tier --target primary
#    owlctl job apply --group sql-tier --target dr
#
# 5. Drift check a group
#    owlctl job diff --group sql-tier --target primary
#
# 6. Single-file overlay (no group needed)
#    owlctl job apply base-job.yaml -o overlay.yaml
