# owlctl Configuration File
# Place this file in your project root or ~/.owlctl/owlctl.yaml

apiVersion: owlctl.veeam.com/v1
kind: Config

# Groups bundle specs with a shared profile and overlay for batch operations.
# Apply a group: owlctl job apply --group db-tier
# Diff a group:  owlctl job diff --group db-tier
groups:
  db-tier:
    description: Database backups — encrypted, 14-day retention, SQL guest processing
    profile: profiles/standard-db-backup.yaml      # kind: Profile — base defaults
    overlay: overlays/enable-encryption.yaml        # kind: Overlay — policy patch
    specs:
      - specs/sql-daily.yaml

  file-tier:
    description: File server backups — 7-day retention, image-level only
    profile: profiles/standard-file-backup.yaml
    specs:
      - specs/file-backup.yaml

# Targets define named VBR server connections.
# Use --target to switch: owlctl job apply --group db-tier --target primary
targets:
  primary:
    url: https://vbr-prod.example.com
    description: Production VBR server

  dr:
    url: https://vbr-dr.example.com
    description: Disaster recovery site

# Usage Examples:
#
# 1. List groups and targets
#    owlctl group list
#    owlctl target list
#
# 2. Show group details (resolved paths, spec count)
#    owlctl group show db-tier
#
# 3. Apply a group (dry-run first)
#    owlctl job apply --group db-tier --dry-run
#    owlctl job apply --group db-tier
#
# 4. Apply a group to a specific target
#    owlctl job apply --group db-tier --target primary
#    owlctl job apply --group db-tier --target dr
#
# 5. Drift check a group
#    owlctl job diff --group db-tier --target primary
#
# 6. Single-file overlay (no group needed)
#    owlctl job apply jobs/database-backup.yaml -o overlays/retention-30d.yaml
